apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: default
spec:
  clusterIP: None   # Headless Service for StatefulSet
  selector:
    app: mongo
  ports:
  - port: 27017
    name: mongo